/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_imp_snakegame_SegmentJNI_SegmentJNI */

#ifndef _Included_com_example_imp_snakegame_SegmentJNI_SegmentJNI
#define _Included_com_example_imp_snakegame_SegmentJNI_SegmentJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_imp_snakegame_SegmentJNI_SegmentJNI
 * Method:    open
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_imp_1snakegame_SegmentJNI_SegmentJNI_open
  (JNIEnv *, jobject);

/*
 * Class:     com_example_imp_snakegame_SegmentJNI_SegmentJNI
 * Method:    print
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_example_imp_1snakegame_SegmentJNI_SegmentJNI_print
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
