/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_imp_snakegame_Piazo_PiazoJNI */

#ifndef _Included_com_example_imp_snakegame_Piazo_PiazoJNI
#define _Included_com_example_imp_snakegame_Piazo_PiazoJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_imp_snakegame_Piazo_PiazoJNI
 * Method:    write
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_example_imp_1snakegame_Piazo_PiazoJNI_write
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
