/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_imp_snakegame_Led_LedJNI */

#ifndef _Included_com_example_imp_snakegame_Led_LedJNI
#define _Included_com_example_imp_snakegame_Led_LedJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_imp_snakegame_Led_LedJNI
 * Method:    on
 * Signature: (C)V
 */
JNIEXPORT void JNICALL Java_com_example_imp_1snakegame_Led_LedJNI_on
  (JNIEnv *, jobject, jchar);

#ifdef __cplusplus
}
#endif
#endif
