/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_imp_snakegame_TextLcd_TextLcdJNI */

#ifndef _Included_com_example_imp_snakegame_TextLcd_TextLcdJNI
#define _Included_com_example_imp_snakegame_TextLcd_TextLcdJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_imp_snakegame_TextLcd_TextLcdJNI
 * Method:    on
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_imp_1snakegame_TextLcd_TextLcdJNI_on
  (JNIEnv *, jobject);

/*
 * Class:     com_example_imp_snakegame_TextLcd_TextLcdJNI
 * Method:    clear
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_imp_1snakegame_TextLcd_TextLcdJNI_clear
  (JNIEnv *, jobject);

/*
 * Class:     com_example_imp_snakegame_TextLcd_TextLcdJNI
 * Method:    print1Line
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_example_imp_1snakegame_TextLcd_TextLcdJNI_print1Line
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_example_imp_snakegame_TextLcd_TextLcdJNI
 * Method:    print2Line
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_example_imp_1snakegame_TextLcd_TextLcdJNI_print2Line
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
